spring.application.name=querypulse-backend

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/querypulse
spring.datasource.username=postgres
spring.datasource.password=admin@123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=8080

# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.security=DEBUG

# ===============================
# JWT CONFIGURATION
# ===============================

jwt.secret=QueryPulseSecretKeyQueryPulseSecretKey123456789

jwt.expiration=86400000  